from practica4repo import repe, promedio2, promedio3, modulo, gritar, elevarCubo, cantDivisores, esPrimo, factoresPrimos, mayorDeDos, mayorDeTres, potencia, sumaDeDivisores, esPerfecto, esAbundante, esPoderoso, esLibreDeCuadrado, siguienteNumeroPrimo, palabraRecuadradaConAsterizcos
import math
a = input("Ingresa una palabra: ")
# x = int(input("Ingresa un numero entero: "))
# y = float(input("Ingresa un numero decimal: "))
# z = float(input("Ingresa un numero real: "))
# w = float(input("Ingresa un numero real: "))
# v = int(input("Ingresa un numero entero positivo: "))

# print(f"\n Act 1) A)B)C)D)\n Raiz de {y} es: {math.sqrt(y)} \n Modulo de {y} es: {abs(y)} \n Modulo de {y}-3 es: {abs(y-3)} \n Raiz del modulo de {y}-5 es: {math.sqrt(abs(y-5))}")
# # print(f"\n Act 3)A)\n {repe(a)}")
# print("\n Act 4)A)\n", promedio2(y, z))
# print("\n Act 4)C)\n", promedio3(y, z, w))
# print("\nAct 5)\n", modulo(y))
# print("\nAct 6)C)\n", gritar("Ouch"))
# print(f"\nAct 7)C)\n 0 al cubo: {elevarCubo(0)} \n 1 al cubo: {elevarCubo(1)} \n 2 al cubo: {elevarCubo(2)} \n 3 al cubo: {elevarCubo(3)} \n 4 al cubo: {elevarCubo(4)} \n 5 al cubo: {elevarCubo(5)} \n 6 al cubo: {elevarCubo(6)} \n -1 al cubo: {elevarCubo(-1)} \n -2 al cubo: {elevarCubo(-2)} \n -3 al cubo: {elevarCubo(-3)} \n -4 al cubo: {elevarCubo(-4)}\n -5 al cubo: {elevarCubo(-5)}") 
# print(f"\nAct 8)A)\n {x} tiene {cantDivisores(x)} divisores")
# print(f"\nAct 8)B)\n {x} {'es primo' if esPrimo(x) else 'no es primo'}")
# print(f"\nAct 8)D)\n {x} tiene los siguientes factores primos: {factoresPrimos(x)}")
# print(f"\nAct 9)A)\n El mayor entre {x} y {y} es {mayorDeDos(x, y)}")
# print(f"\nAct 9)B)\n El mayor entre {x}, {y} y {z} es: {mayorDeTres(x, y, z)}")
# print("\nAct 10)\n", potencia(x, y))
# print("\nAct 11)A)\n", sumaDeDivisores(x))
# print(f"\nAct 11)B)\n {x} {'es perfecto' if esPerfecto(x) else 'no es perfecto'}")
# print(f"\nAct 11)C)\n {x} {'es abundante' if esAbundante(x) else 'no es abundante'}")
# print(f"\nAct 12)\n {x} {'es poderoso' if esPoderoso(x) else 'no es poderoso'}")
# print(f"\nAct 13)\n {x} {'es libre de cuadrados' if esLibreDeCuadrado(x) else 'no es libre de cuadrados'}")
# print(f"\nAct 11)A)\n El siguiente numero primo a {v} es {siguienteNumeroPrimo(v)}")
print(f"\nAct 15)\n")
palabraRecuadradaConAsterizcos(a)