print("act 6")
print("mi primer programa python")
print("\nact 7")
print("v\ne\nr\nt\ni\nc\na\nl")
print("\nact 8")
print("*****\n*   *\n*   *\n*   *\n*****")
print("\nact 9")
print("*\n***\n*****\n*******\n*********")
print("\nact 10")
print(input("Tu nombre es: "))
print("\nact 11")
x = input("Ingresa un valor: ")
print(f"********************\n* El resultado es: {x} \n********************")